services:
  nft-store:
    depends_on:
      postgres:
        condition: service_started

    image: ghcr.io/lunaetco/devcontainer

    environment:
      # Apps
      DATABASE_URL: postgresql://postgres:postgres@postgres/postgres?sslmode=disable

      # PostgreSQL psql client
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres

    volumes:
      - ..:/workspaces/nft-store:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres:
    image: ghcr.io/lunaetco/postgres:main
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
